[package]
name = "mrs-matrix"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"


[dependencies]
crossterm = "0.23.2"
coolor = {version = "0.5.0", features=["crossterm"]}
rand = "0.8.5"